# simulation final time and time step
tf: 60.0
dt: 0.004
use_random_seed: false
accurate_integration: true
log_directory: "../logs"

# Truth Configuration
use_accel_truth: false
use_gyro_truth: false
use_camera_truth: false

x0: [0, 0, -1,   # POS
     1, 0, 0, 0, # ATT
     0, 0, 0,    # VEL 
     0, 0, 0,    # OMEGA 
     0, 0, 0]    # ACC


# Controller Configuration
throttle_eq: 0.5
mass: 1.0
max_thrust: 19.6133
inertia: [0.02, 0.02, 0.04]
linear_drag: [0.1, 0.1, 0.01]
angular_drag: [0.001, 0.001, 0.001]

Kp: [1, 1, 1]
Kd: [0.0, 0.0, 0.0]
Kv: [2, 2, 2]

roll_kp: 10.0
roll_ki: 0.0
roll_kd: 1.0
pitch_kp: 10.0
pitch_ki: 0.0
pitch_kd: 1.0
yaw_rate_kp: 1.0
yaw_rate_ki: 0.0
yaw_rate_kd: 0.0
max_roll: 1.0
max_pitch: 1.0
max_yaw_rate: 1.5
max_throttle: 1.0
max_vel: 5.0
max_tau_x: 1.0
max_tau_y: 1.0
max_tau_z: 1.0

# 0: waypoints
# 1: trajectory
path_type: 1

waypoints: [0, 0, -4, 0,
            10, 0, -4, 0,
            10, 0, -8, 1.57,
            10, 10, -8, 1.57,
            10, 10, -4, 3.14,
            -10, 10, -4, 3.14,
            -10, 10, -8, -1.57,
            -10, -10, -8, -1.57,
            -10, -10, -4, 0,
            10, -10, -4, 0,
            10, 0, -4, 1.57]
waypoint_threshold: 0.1
waypoint_velocity_threshold: 0.5

traj_delta_north: 10
traj_delta_east: 10
traj_delta_alt: -4
traj_delta_yaw: 1.5
traj_nom_north: 0
traj_nom_east: 0
traj_nom_alt: 5
traj_nom_yaw: 0
traj_north_period: 20
traj_east_period: 20
traj_alt_period: 20
traj_yaw_period: 20

# Environment Setup
enable_wind: false # Turn wind on and off
wind_init_stdev: 1.0 # Variation on the initial wind direction
wind_walk_stdev: 0.2 # Amount of random walk in wind components
wall_pts_density: 5 # Average points per square meter of wall
wall_max_deviation: 0.2 # Maximum deviation from wall center
wall_north_dim: 30 # Total room length in north dimension
wall_east_dim: 30 # Total room length in east dimension
wall_height: 10 # Total room height


# Sensor Configuration

## IMU
imu_update_rate: 250

accel_noise_stdev: 0.5
accel_bias_init_bound: 0.5
accel_walk_stdev: 0.01

gyro_noise_stdev: 0.1
gyro_bias_init_bound: 0.2
gyro_walk_stdev: 0.001

## Camera
camera_update_rate: 50
pixel_noise_stdev: 0.5
image_size: [640, 480]
camera_matrix: [480,   0, 320,
                  0, 480, 240,
                  0,   0,   1]
q_bc: [0.5, 0.5, 0.5, 0.5]
p_bc: [0.1, 0, 0.05]

## Depth
## Altimeter
## Barometer
## Magnetometer
## GPS


# Estimator Configuration
xhat0: [0, 0, -1,   # POS
        1, 0, 0, 0, # ATT
        0, 0, 0,    # VEL
        0, 0, 0,    # OMEGA
        0, 0, 0]    # ACC

P0_diag: [0.001, 0.001, 0.001, # POS
          0.001, 0.001, 0.001, # ATT
          0.001, 0.001, 0.001, # VEL
          0.1, 0.1, 0.1, # OMEGA
          0.1, 0.1, 0.1] # ACC

Qx_diag: [0.0, 0.0, 0.0, # POS
          0.0, 0.0, 0.0, # ATT
          0.0, 0.0, 0.0, # VEL
          0.0, 0.0, 0.0, # OMEGA
          0.0, 0.0, 0.0] # ACC

Qu_diag: [0.01, 0.01, 0.01, # OMEGA
          0.25, 0.25, 0.25] # ACC

R_vo_diag: [0.002, 0.002, # Translation Direction
            0.0002, 0.0002, 0.0002] # Rotation

lambda: [1, 1, 1, # POS
         1, 1, 1, # ATT
         1, 1, 1, # VEL
         1, 1, 1, # OMEGA
         1, 1, 1] # ACC

pixel_disparity_threshold: 20
max_tracked_features: 100
min_kf_feature_matches: 50
