# simulation final time and time step
tf: 10.0
dt: 0.004

log_directory: "../logs"


# Truth Configuration
use_accel_truth: false
use_gyro_truth: false
use_camera_truth: false
use_altimeter_truth: false
use_depth_truth: false

accurate_integration: false

x0: [0, 0, -1,   # POS
     1, 0, 0, 0, # ATT
     0, 0, 0,    # VEL 
     0, 0, 0,    # OMEGA 
     0, 0, 0]    # ACC


# Controller Configuration
throttle_eq: 0.5
mass: 0.6
max_thrust: 19.6133
inertia: [0.02, 0.02, 0.04]
linear_drag: [0.01, 0.01, 0.001]
angular_drag: [0.0001, 0.0001, 0.0001]

Kp: [1, 1, 5]
Kd: [0.001, 0.001, 0.001]
Kv: [2, 2, 5]

roll_kp: 10.0
roll_ki: 0.0
roll_kd: 1.0
pitch_kp: 10.0
pitch_ki: 0.0
pitch_kd: 1.0
yaw_rate_kp: 1.0
yaw_rate_ki: 0.0
yaw_rate_kd: 0.0
max_roll: 1.0
max_pitch: 1.0
max_yaw_rate: 1.0
max_throttle: 1.0
max_vel: 5.0
max_tau_x: 1.0
max_tau_y: 1.0
max_tau_z: 1.0

waypoints: [10, 0, -5, .705,
            10, 10, -4, 3.0,
            -10, 10, -5.5, -1.5,
            -10, -7, -5, .80,
            -8, -12, -4.5, -2.3,
            8, -5, -4, 1.7]
waypoint_threshold: 0.1
waypoint_velocity_threshold: 0.5


# Environment Setup
wind_vel: [0,0,0]
wind_vel_stdev: 0.5
wall_density: 12 # Average points per square meter of wall
wall_max_offset: 0.2 # Points are distributed normally about the wall
wall_0: [-12, -15, -8, # bottom left
         1, 0, 0, # normal
         30, 8] # width, height
wall_1: [-12, 15, -8, # bottom left
         0, 1, 0, # normal
         24, 8] # width, height
wall_2: [12, -15, -8, # bottom left
         1, 0, 0, # normal
         30, 8] # width, height
wall_3: [-12, -15, -8, # bottom left
         0, 1, 0, # normal
         24, 8] # width, height
wall_4: [-12, -15, 0, # bottom left
         0, 0, 1, # normal
         24, 30] # width, height
wall_5: [-12, -15, -8, # bottom left
         0, 0, 1, # normal
         24, 30] # width, height


# Sensor Configuration

## Active Measurements
feature_update_active: true
drag_update_active: false
attitude_update_active: false
depth_update_active: false
altimeter_update_active: false

## IMU
imu_update_rate: 250

accel_init_stdev: 0.3
accel_noise_stdev: 0.5
accel_bias_walk: 0.01

gyro_init_stdev: 0.1
gyro_noise_stdev: 0.1
gyro_bias_walk: 0.001

## Camera
camera_update_rate: 30
pixel_noise_stdev: 0.5
focal_len: [250.0, 250.0]
cam_center: [320, 240]
image_size: [640, 480]
q_b_c: [1, 0, 0, 0]
p_b_c: [0, 0, 0]

## Altimeter
altimeter_update_rate: 100
altimeter_noise_stdev: 0.2

## Depth
depth_update_rate: 30
depth_noise_stdev: 0.5

## Attitude
attitude_update_rate: 100

